//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdeaBranch.App.Resources {
    using System;
    using System.Reflection;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("IdeaBranch.App.Resources.AppResources", typeof(AppResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string MainPage_Headline {
            get {
                return ResourceManager.GetString("MainPage_Headline", resourceCulture);
            }
        }

        public static string MainPage_WelcomeMessage {
            get {
                return ResourceManager.GetString("MainPage_WelcomeMessage", resourceCulture);
            }
        }

        public static string MainPage_CounterButton {
            get {
                return ResourceManager.GetString("MainPage_CounterButton", resourceCulture);
            }
        }

        public static string MainPage_CounterClickedOnce {
            get {
                return ResourceManager.GetString("MainPage_CounterClickedOnce", resourceCulture);
            }
        }

        public static string MainPage_CounterClickedMultiple {
            get {
                return ResourceManager.GetString("MainPage_CounterClickedMultiple", resourceCulture);
            }
        }

        public static string AppShell_Home {
            get {
                return ResourceManager.GetString("AppShell_Home", resourceCulture);
            }
        }

        public static string AppShell_ResilienceTest {
            get {
                return ResourceManager.GetString("AppShell_ResilienceTest", resourceCulture);
            }
        }

        public static string AppShell_TopicTree {
            get {
                return ResourceManager.GetString("AppShell_TopicTree", resourceCulture);
            }
        }

        public static string AppShell_Map {
            get {
                return ResourceManager.GetString("AppShell_Map", resourceCulture);
            }
        }

        public static string AppShell_Timeline {
            get {
                return ResourceManager.GetString("AppShell_Timeline", resourceCulture);
            }
        }

        public static string AppShell_Notifications {
            get {
                return ResourceManager.GetString("AppShell_Notifications", resourceCulture);
            }
        }

        public static string AppShell_Settings {
            get {
                return ResourceManager.GetString("AppShell_Settings", resourceCulture);
            }
        }

        public static string ResilienceTestPage_Title {
            get {
                return ResourceManager.GetString("ResilienceTestPage_Title", resourceCulture);
            }
        }

        public static string ResilienceTestPage_Headline {
            get {
                return ResourceManager.GetString("ResilienceTestPage_Headline", resourceCulture);
            }
        }

        public static string ResilienceTestPage_Description {
            get {
                return ResourceManager.GetString("ResilienceTestPage_Description", resourceCulture);
            }
        }

        public static string ResilienceTestPage_GetButton {
            get {
                return ResourceManager.GetString("ResilienceTestPage_GetButton", resourceCulture);
            }
        }

        public static string ResilienceTestPage_PostButton {
            get {
                return ResourceManager.GetString("ResilienceTestPage_PostButton", resourceCulture);
            }
        }

        public static string ResilienceTestPage_RetryButton {
            get {
                return ResourceManager.GetString("ResilienceTestPage_RetryButton", resourceCulture);
            }
        }

        public static string ResilienceTestPage_CircuitBreakerButton {
            get {
                return ResourceManager.GetString("ResilienceTestPage_CircuitBreakerButton", resourceCulture);
            }
        }

        public static string ResilienceTestPage_DelayButton {
            get {
                return ResourceManager.GetString("ResilienceTestPage_DelayButton", resourceCulture);
            }
        }

        public static string ResilienceTestPage_ResultsLabel {
            get {
                return ResourceManager.GetString("ResilienceTestPage_ResultsLabel", resourceCulture);
            }
        }

        public static string ResilienceTestPage_InstructionsLabel {
            get {
                return ResourceManager.GetString("ResilienceTestPage_InstructionsLabel", resourceCulture);
            }
        }

        public static string ResilienceTestPage_InstructionsText {
            get {
                return ResourceManager.GetString("ResilienceTestPage_InstructionsText", resourceCulture);
            }
        }

        public static string SettingsPage_Title {
            get {
                return ResourceManager.GetString("SettingsPage_Title", resourceCulture);
            }
        }

        public static string SettingsPage_UserSettingsTitle {
            get {
                return ResourceManager.GetString("SettingsPage_UserSettingsTitle", resourceCulture);
            }
        }

        public static string SettingsPage_UserSettingsComingSoon {
            get {
                return ResourceManager.GetString("SettingsPage_UserSettingsComingSoon", resourceCulture);
            }
        }

        public static string SettingsPage_ProjectSettingsTitle {
            get {
                return ResourceManager.GetString("SettingsPage_ProjectSettingsTitle", resourceCulture);
            }
        }

        public static string SettingsPage_ProjectSettingsComingSoon {
            get {
                return ResourceManager.GetString("SettingsPage_ProjectSettingsComingSoon", resourceCulture);
            }
        }

        public static string SettingsPage_DisplaySettingsTitle {
            get {
                return ResourceManager.GetString("SettingsPage_DisplaySettingsTitle", resourceCulture);
            }
        }

        public static string SettingsPage_LanguageLabel {
            get {
                return ResourceManager.GetString("SettingsPage_LanguageLabel", resourceCulture);
            }
        }

        public static string SettingsPage_LanguageRestartNote {
            get {
                return ResourceManager.GetString("SettingsPage_LanguageRestartNote", resourceCulture);
            }
        }

        public static string SettingsPage_SearchFilterSettingsTitle {
            get {
                return ResourceManager.GetString("SettingsPage_SearchFilterSettingsTitle", resourceCulture);
            }
        }

        public static string SettingsPage_SearchFilterSettingsComingSoon {
            get {
                return ResourceManager.GetString("SettingsPage_SearchFilterSettingsComingSoon", resourceCulture);
            }
        }

        public static string SettingsPage_IntegrationSettingsTitle {
            get {
                return ResourceManager.GetString("SettingsPage_IntegrationSettingsTitle", resourceCulture);
            }
        }

        public static string SettingsPage_LlmProviderLabel {
            get {
                return ResourceManager.GetString("SettingsPage_LlmProviderLabel", resourceCulture);
            }
        }

        public static string SettingsPage_LmStudioConfigurationTitle {
            get {
                return ResourceManager.GetString("SettingsPage_LmStudioConfigurationTitle", resourceCulture);
            }
        }

        public static string SettingsPage_EndpointLabel {
            get {
                return ResourceManager.GetString("SettingsPage_EndpointLabel", resourceCulture);
            }
        }

        public static string SettingsPage_ModelLabel {
            get {
                return ResourceManager.GetString("SettingsPage_ModelLabel", resourceCulture);
            }
        }

        public static string SettingsPage_AzureOpenAiConfigurationTitle {
            get {
                return ResourceManager.GetString("SettingsPage_AzureOpenAiConfigurationTitle", resourceCulture);
            }
        }

        public static string SettingsPage_DeploymentLabel {
            get {
                return ResourceManager.GetString("SettingsPage_DeploymentLabel", resourceCulture);
            }
        }

        public static string SettingsPage_ApiKeyLabel {
            get {
                return ResourceManager.GetString("SettingsPage_ApiKeyLabel", resourceCulture);
            }
        }

        public static string SettingsPage_ApiKeyPlaceholder {
            get {
                return ResourceManager.GetString("SettingsPage_ApiKeyPlaceholder", resourceCulture);
            }
        }

        public static string SettingsPage_NotificationSettingsTitle {
            get {
                return ResourceManager.GetString("SettingsPage_NotificationSettingsTitle", resourceCulture);
            }
        }

        public static string SettingsPage_InAppNotificationsLabel {
            get {
                return ResourceManager.GetString("SettingsPage_InAppNotificationsLabel", resourceCulture);
            }
        }

        public static string SettingsPage_InAppNotificationsDescription {
            get {
                return ResourceManager.GetString("SettingsPage_InAppNotificationsDescription", resourceCulture);
            }
        }

        public static string SettingsPage_PushNotificationsLabel {
            get {
                return ResourceManager.GetString("SettingsPage_PushNotificationsLabel", resourceCulture);
            }
        }

        public static string SettingsPage_PushNotificationsDescription {
            get {
                return ResourceManager.GetString("SettingsPage_PushNotificationsDescription", resourceCulture);
            }
        }

        public static string SettingsPage_AiSafetySettingsTitle {
            get {
                return ResourceManager.GetString("SettingsPage_AiSafetySettingsTitle", resourceCulture);
            }
        }

        public static string SettingsPage_AiSafetySettingsComingSoon {
            get {
                return ResourceManager.GetString("SettingsPage_AiSafetySettingsComingSoon", resourceCulture);
            }
        }

        public static string SettingsPage_ImportExportSettingsTitle {
            get {
                return ResourceManager.GetString("SettingsPage_ImportExportSettingsTitle", resourceCulture);
            }
        }

        public static string SettingsPage_ImportExportSettingsComingSoon {
            get {
                return ResourceManager.GetString("SettingsPage_ImportExportSettingsComingSoon", resourceCulture);
            }
        }

        public static string SettingsCategory_User {
            get {
                return ResourceManager.GetString("SettingsCategory_User", resourceCulture);
            }
        }

        public static string SettingsCategory_Project {
            get {
                return ResourceManager.GetString("SettingsCategory_Project", resourceCulture);
            }
        }

        public static string SettingsCategory_Display {
            get {
                return ResourceManager.GetString("SettingsCategory_Display", resourceCulture);
            }
        }

        public static string SettingsCategory_SearchFilter {
            get {
                return ResourceManager.GetString("SettingsCategory_SearchFilter", resourceCulture);
            }
        }

        public static string SettingsCategory_Integrations {
            get {
                return ResourceManager.GetString("SettingsCategory_Integrations", resourceCulture);
            }
        }

        public static string SettingsCategory_Notifications {
            get {
                return ResourceManager.GetString("SettingsCategory_Notifications", resourceCulture);
            }
        }

        public static string SettingsCategory_AiSafety {
            get {
                return ResourceManager.GetString("SettingsCategory_AiSafety", resourceCulture);
            }
        }

        public static string SettingsCategory_ImportExport {
            get {
                return ResourceManager.GetString("SettingsCategory_ImportExport", resourceCulture);
            }
        }

        public static string NotificationsPage_Title {
            get {
                return ResourceManager.GetString("NotificationsPage_Title", resourceCulture);
            }
        }

        public static string NotificationsPage_Header {
            get {
                return ResourceManager.GetString("NotificationsPage_Header", resourceCulture);
            }
        }

        public static string NotificationsPage_ClearAllButton {
            get {
                return ResourceManager.GetString("NotificationsPage_ClearAllButton", resourceCulture);
            }
        }

        public static string NotificationsPage_EmptyView {
            get {
                return ResourceManager.GetString("NotificationsPage_EmptyView", resourceCulture);
            }
        }

        public static string NotificationsPage_MarkReadButton {
            get {
                return ResourceManager.GetString("NotificationsPage_MarkReadButton", resourceCulture);
            }
        }

        public static string NotificationsPage_DeleteButton {
            get {
                return ResourceManager.GetString("NotificationsPage_DeleteButton", resourceCulture);
            }
        }

        public static string VersionHistoryPage_Title {
            get {
                return ResourceManager.GetString("VersionHistoryPage_Title", resourceCulture);
            }
        }

        public static string VersionHistoryPage_HistoryFor {
            get {
                return ResourceManager.GetString("VersionHistoryPage_HistoryFor", resourceCulture);
            }
        }

        public static string VersionHistoryPage_ByAuthor {
            get {
                return ResourceManager.GetString("VersionHistoryPage_ByAuthor", resourceCulture);
            }
        }

        public static string VersionHistoryPage_PromptLabel {
            get {
                return ResourceManager.GetString("VersionHistoryPage_PromptLabel", resourceCulture);
            }
        }

        public static string VersionHistoryPage_ResponseLabel {
            get {
                return ResourceManager.GetString("VersionHistoryPage_ResponseLabel", resourceCulture);
            }
        }

        public static string VersionHistoryPage_EmptyState {
            get {
                return ResourceManager.GetString("VersionHistoryPage_EmptyState", resourceCulture);
            }
        }

        public static string TopicNodeDetailPage_Title {
            get {
                return ResourceManager.GetString("TopicNodeDetailPage_Title", resourceCulture);
            }
        }

        public static string TopicNodeDetailPage_TitleLabel {
            get {
                return ResourceManager.GetString("TopicNodeDetailPage_TitleLabel", resourceCulture);
            }
        }

        public static string TopicNodeDetailPage_TitlePlaceholder {
            get {
                return ResourceManager.GetString("TopicNodeDetailPage_TitlePlaceholder", resourceCulture);
            }
        }

        public static string TopicNodeDetailPage_PromptLabel {
            get {
                return ResourceManager.GetString("TopicNodeDetailPage_PromptLabel", resourceCulture);
            }
        }

        public static string TopicNodeDetailPage_PromptPlaceholder {
            get {
                return ResourceManager.GetString("TopicNodeDetailPage_PromptPlaceholder", resourceCulture);
            }
        }

        public static string TopicNodeDetailPage_ResponseLabel {
            get {
                return ResourceManager.GetString("TopicNodeDetailPage_ResponseLabel", resourceCulture);
            }
        }

        public static string TopicNodeDetailPage_ResponsePlaceholder {
            get {
                return ResourceManager.GetString("TopicNodeDetailPage_ResponsePlaceholder", resourceCulture);
            }
        }

        public static string TopicNodeDetailPage_RetryButton {
            get {
                return ResourceManager.GetString("TopicNodeDetailPage_RetryButton", resourceCulture);
            }
        }

        public static string TopicNodeDetailPage_ViewHistoryButton {
            get {
                return ResourceManager.GetString("TopicNodeDetailPage_ViewHistoryButton", resourceCulture);
            }
        }

        public static string TopicNodeDetailPage_GenerateResponseButton {
            get {
                return ResourceManager.GetString("TopicNodeDetailPage_GenerateResponseButton", resourceCulture);
            }
        }

        public static string TopicNodeDetailPage_GenerateTitleButton {
            get {
                return ResourceManager.GetString("TopicNodeDetailPage_GenerateTitleButton", resourceCulture);
            }
        }

        public static string TopicNodeDetailPage_CancelButton {
            get {
                return ResourceManager.GetString("TopicNodeDetailPage_CancelButton", resourceCulture);
            }
        }

        public static string TopicNodeDetailPage_SaveButton {
            get {
                return ResourceManager.GetString("TopicNodeDetailPage_SaveButton", resourceCulture);
            }
        }

        public static string TopicNodeDetailPage_AnnotateButton {
            get {
                return ResourceManager.GetString("TopicNodeDetailPage_AnnotateButton", resourceCulture);
            }
        }

        public static string TopicNodeDetailPage_AnnotationsLabel {
            get {
                return ResourceManager.GetString("TopicNodeDetailPage_AnnotationsLabel", resourceCulture);
            }
        }

        public static string TopicNodeDetailPage_ShowCommentsLabel {
            get {
                return ResourceManager.GetString("TopicNodeDetailPage_ShowCommentsLabel", resourceCulture);
            }
        }

        public static string TopicNodeDetailPage_NoAnnotationsLabel {
            get {
                return ResourceManager.GetString("TopicNodeDetailPage_NoAnnotationsLabel", resourceCulture);
            }
        }

        public static string AnnotationEditPage_Title {
            get {
                return ResourceManager.GetString("AnnotationEditPage_Title", resourceCulture);
            }
        }

        public static string AnnotationEditPage_SelectedTextLabel {
            get {
                return ResourceManager.GetString("AnnotationEditPage_SelectedTextLabel", resourceCulture);
            }
        }

        public static string AnnotationEditPage_CommentLabel {
            get {
                return ResourceManager.GetString("AnnotationEditPage_CommentLabel", resourceCulture);
            }
        }

        public static string AnnotationEditPage_CommentPlaceholder {
            get {
                return ResourceManager.GetString("AnnotationEditPage_CommentPlaceholder", resourceCulture);
            }
        }

        public static string AnnotationEditPage_TagsLabel {
            get {
                return ResourceManager.GetString("AnnotationEditPage_TagsLabel", resourceCulture);
            }
        }

        public static string AnnotationEditPage_TagsNote {
            get {
                return ResourceManager.GetString("AnnotationEditPage_TagsNote", resourceCulture);
            }
        }

        public static string AnnotationEditPage_NoTagsLabel {
            get {
                return ResourceManager.GetString("AnnotationEditPage_NoTagsLabel", resourceCulture);
            }
        }

        public static string AnnotationEditPage_OptionalValuesLabel {
            get {
                return ResourceManager.GetString("AnnotationEditPage_OptionalValuesLabel", resourceCulture);
            }
        }

        public static string AnnotationEditPage_NumericValueLabel {
            get {
                return ResourceManager.GetString("AnnotationEditPage_NumericValueLabel", resourceCulture);
            }
        }

        public static string AnnotationEditPage_NumericValuePlaceholder {
            get {
                return ResourceManager.GetString("AnnotationEditPage_NumericValuePlaceholder", resourceCulture);
            }
        }

        public static string AnnotationEditPage_TemporalValueLabel {
            get {
                return ResourceManager.GetString("AnnotationEditPage_TemporalValueLabel", resourceCulture);
            }
        }

        public static string AnnotationEditPage_GeospatialValueLabel {
            get {
                return ResourceManager.GetString("AnnotationEditPage_GeospatialValueLabel", resourceCulture);
            }
        }

        public static string AnnotationEditPage_GeospatialValuePlaceholder {
            get {
                return ResourceManager.GetString("AnnotationEditPage_GeospatialValuePlaceholder", resourceCulture);
            }
        }

        public static string AnnotationEditPage_SaveButton {
            get {
                return ResourceManager.GetString("AnnotationEditPage_SaveButton", resourceCulture);
            }
        }

        public static string AnnotationEditPage_CancelButton {
            get {
                return ResourceManager.GetString("AnnotationEditPage_CancelButton", resourceCulture);
            }
        }

        public static string AnnotationEditPage_DeleteButton {
            get {
                return ResourceManager.GetString("AnnotationEditPage_DeleteButton", resourceCulture);
            }
        }

        public static string TopicTreePage_Title {
            get {
                return ResourceManager.GetString("TopicTreePage_Title", resourceCulture);
            }
        }

        public static string MapPage_Title {
            get {
                return ResourceManager.GetString("MapPage_Title", resourceCulture);
            }
        }

        public static string MapPage_Content {
            get {
                return ResourceManager.GetString("MapPage_Content", resourceCulture);
            }
        }

        public static string TimelinePage_Title {
            get {
                return ResourceManager.GetString("TimelinePage_Title", resourceCulture);
            }
        }

        public static string TimelinePage_Content {
            get {
                return ResourceManager.GetString("TimelinePage_Content", resourceCulture);
            }
        }
    }
}

